api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: lib
env_make: ~
env_prep: get-composer
env_post: ci-coveralls,ci-codacy
php_conf: timezone
php_exts: ~
app_prep: dep-composer
app_post: ~
app_path: ~
pkg_name: cocoa-transformer-library
pkg_desc: "Simple transformer and cacheable transformer interfaces with accompanying abstract implementations."
pkg_bndl: false
